#
# Variablen helfen in Makefiles copy&paste zu verringern und die "Rezepte"
# uebersichtlicher zu gestalten.
#

CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

# Rezept wird mit `make blatt02_1.exe` aufgerufen, Windows-Nutzer muessen vor
# `./blatt02_1.exe` ggf. das `./` entfernen.

blatt03_1.exe: blatt03_1.c
	$(CC) $(CFLAGS) -o blatt03_1.exe blatt03_1.c
	./blatt03_1.exe

blatt03_2.exe: blatt03_2.c
	$(CC) $(CFLAGS) -o blatt03_2.exe blatt03_2.c
	./blatt03_2.exe

blatt03_3a.exe: blatt03_3a.c
	$(CC) $(CFLAGS) -o blatt03_3a.exe blatt03_3a.c
	./blatt03_3a.exe

blatt03_3b.exe: blatt03_3b.c
	$(CC) $(CFLAGS) -o blatt03_3b.exe blatt03_3b.c
	./blatt03_3b.exe

blatt03_3c.exe: blatt03_3c.c
	$(CC) $(CFLAGS) -o blatt03_3c.exe blatt03_3c.c
	./blatt03_3c.exe
