#
# Variablen helfen in Makefiles copy&paste zu verringern und die "Rezepte"
# uebersichtlicher zu gestalten.
#

CC = gcc
CFLAGS = -std=c99 -pedantic -Wall -Wextra

# Rezept wird mit `make blatt02_1.exe` aufgerufen, Windows-Nutzer muessen vor
# `./blatt02_1.exe` ggf. das `./` entfernen.

blatt02_1.exe: blatt02_1.c
	$(CC) $(CFLAGS) -o blatt02_1.exe blatt02_1.c
	./blatt02_1.exe

blatt02_2.exe: blatt02_2.c
	$(CC) $(CFLAGS) -o blatt02_2.exe blatt02_2.c
	./blatt02_2.exe

blatt02_3.exe: blatt02_3.c
	$(CC) $(CFLAGS) -o blatt02_3.exe blatt02_3.c
	./blatt02_3.exe

blatt02_4.exe: blatt02_4.c
	$(CC) $(CFLAGS) -o blatt02_4.exe blatt02_4.c
	./blatt02_4.exe

blatt02_5.exe: blatt02_5.c
	$(CC) $(CFLAGS) -o blatt02_5.exe blatt02_5.c
	./blatt02_5.exe

blatt02_6.exe: blatt02_6.c
	$(CC) $(CFLAGS) -o blatt02_6.exe blatt02_6.c
	./blatt02_6.exe

blatt02_7.exe: blatt02_7.c
	$(CC) $(CFLAGS) -o blatt02_7.exe blatt02_7.c
	./blatt02_7.exe

blatt02_8.exe: blatt02_8.c
	$(CC) $(CFLAGS) -o blatt02_8.exe blatt02_8.c
	./blatt02_8.exe

blatt02_9.exe: blatt02_9.c
	$(CC) $(CFLAGS) -o blatt02_9.exe blatt02_9.c
	./blatt02_9.exe

blatt02_10.exe: blatt02_10.c
	$(CC) $(CFLAGS) -o blatt02_10.exe blatt02_10.c
	./blatt02_10.exe
